/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaTextMenu */

#ifndef _Included_JavaTextMenu
#define _Included_JavaTextMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaTextMenu
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_JavaTextMenu_calculateSTDDev
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JavaTextMenu
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_JavaTextMenu_calculateMean
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
